on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to create, e.g., "3.11.1rc1"'
        required: true
        type: string

jobs:
  make-release:
    runs-on: ubuntu-latest
  steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Start the build process
      run: echo  Start building version ${ input.version } from branch ${ branch }
    - run: pwd
    - run: ls ./scripts
